package by.tr.web.domain;

public enum Parameters {
    COMMAND,

    SAX, StAX, DOM,

    SNS_STUDENTS,
    STUDENT, FATHER, MOTHER,
    SURNAME, FIRST_NAME, PATRONYMIC,
    BROTHERS_AMOUNT, SISTERS_AMOUNT,

    FATHER_NAMESPACE,
    FNS_SURNAME, FNS_FIRST_NAME, FNS_PATRONYMIC,
    FNS_SALARY,

    MOTHER_NAMESPACE,
    MNS_SURNAME, MNS_FIRST_NAME, MNS_PATRONYMIC,
    MNS_SALARY

}
