package by.tr.web.domain;

public enum Parameters {
    COMMAND,

    SAX, STAX, DOM, NEXT_PAGE, PREVIOUS_PAGE,

    SNS_STUDENTS,
    STUDENT, FATHER, MOTHER,
    ID, SURNAME, FIRST_NAME, PATRONYMIC,
    BROTHERS_AMOUNT, SISTERS_AMOUNT,

    SALARY,


    FNS,
    FNS_SURNAME, FNS_FIRST_NAME, FNS_PATRONYMIC,
    FNS_SALARY,

    MNS,
    MNS_SURNAME, MNS_FIRST_NAME, MNS_PATRONYMIC,
    MNS_SALARY,

    RECORDS_NUMBER, CURRENT_PAGE, PAGE

}
